Immo_Demo/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IMMO.DAL;
using IMMO.BLL;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.Resources;
using Kendo.Mvc.Infrastructure;
using System.Data.Entity;
using Immo_Demo.Models;

namespace Immo_Demo.Controllers
{
    public class ArticlesController : Controller
    {
        IMMODEMOEntities ctxt = new IMMODEMOEntities();

        private IFamArtBuisness bo1 = new FamArticlebuisness();
        private IFamMerebuisness bo2 = new FamMereArticleBuisness();

        //***************************************Controlleur CRUD Famille***************
        public ActionResult GetAllF(string FAMILLEM, [DataSourceRequest] DataSourceRequest request)
        {
            var Articles = bo1.Afficher();
            if (FAMILLEM != "")

                Articles = bo1.TrouverParMere(FAMILLEM);
           
            
            return Json(Articles.ToDataSourceResult(request, record => new
            {
                record.CODE,
                record.LIBELLE,
                record.COMPTE,
                record.FAMILLEM,
              
            }), JsonRequestBehavior.AllowGet);
        }
        //***********************************************************************************

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult AddF([DataSourceRequest] DataSourceRequest request,IMMO_FAMILLE f)
        {
            try { 
            if (f != null && ModelState.IsValid)
            {
                bo1.Ajouter(f);

                ctxt.SaveChanges();
            }
            return Json(new[] { f }.ToDataSourceResult(request, ModelState));
            }
            catch { return View(); }
        }
        //**************************************************************************************

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UpdateF([DataSourceRequest] DataSourceRequest request, IMMO_FAMILLE f)
        {
            try { 
            if (f != null && ModelState.IsValid)
            {
                bo1.Mettre_A_Jour(f);

                ctxt.SaveChanges();
            }
            return Json(ModelState.ToDataSourceResult());
            }
            catch { return View(); }
        }


        //*****************************************************************
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult DeleteF([DataSourceRequest] DataSourceRequest request, IMMO_FAMILLE f)
        {
            try { 
            if (f != null && ModelState.IsValid)
            {
                bo1.Supprimer(f);
                ctxt.SaveChanges();
            }
            return Json(ModelState.ToDataSourceResult());
            }
            catch { return View(); }
        }
        //*********************************************************
        //***************************************Controlleur CRUD Famille Mere***************
        public ActionResult GetAllFm([DataSourceRequest] DataSourceRequest request)
        {

            var Articles = bo2.Afficher();
            return Json(Articles.ToDataSourceResult(request, record => new
            {
                record.CODE,
                record.LIBELLE,
              

            }), JsonRequestBehavior.AllowGet);
        }
        //***********************************************************************************

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult AddFm([DataSourceRequest] DataSourceRequest request, IMMO_FAMILLEM f)
        {
            try
            {
                if (f != null && ModelState.IsValid)
                {
                    bo2.Ajouter(f);

                    ctxt.SaveChanges();
                }
                return Json(new[] { f }.ToDataSourceResult(request, ModelState));
            }
            catch { return View(); }
        }
        //**************************************************************************************

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UpdateFm([DataSourceRequest] DataSourceRequest request, IMMO_FAMILLEM f)
        {
            try { 
            if (f != null && ModelState.IsValid)
            {
                bo2.Mettre_A_Jour(f);

                ctxt.SaveChanges();
            }
            return Json(ModelState.ToDataSourceResult());
            }
            catch { return View(); }
        }


        //*****************************************************************
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult DeleteFm([DataSourceRequest] DataSourceRequest request, IMMO_FAMILLEM f)
        {
            try { 
            if (f != null && ModelState.IsValid)
            {
                bo2.Supprimer(f);
                ctxt.SaveChanges();
            }
            return Json(ModelState.ToDataSourceResult());
            }
            catch { return View(); }
        }
        //*********************************************************
        public JsonResult GetFamilleMere()
        {    //initialisation de context de base de donnees
            IMMODEMOEntities ctxt = new IMMODEMOEntities();
            return Json(ctxt.IMMO_FAMILLEM.Select(c => new { ID = c.CODE, Name= c.LIBELLE }).OrderBy(o => o.ID).ToList(), JsonRequestBehavior.AllowGet);
        }
        //********************************************************************
        public JsonResult GetFamille()
        {    //initialisation de context de base de donnees
            IMMODEMOEntities ctxt = new IMMODEMOEntities();
            return Json(ctxt.IMMO_FAMILLE.Select(c => new { ID = c.CODE, Name = c.LIBELLE }).OrderBy(o => o.ID).ToList(), JsonRequestBehavior.AllowGet);
        }
        //********************************************************************
        public JsonResult GetArticlesN()
        {    //initialisation de context de base de donnees
            IMMODEMOEntities ctxt = new IMMODEMOEntities();
            return Json(ctxt.IMMO_ARTICLE.Select(c => new { ID = c.CODE.ToString(), NAME = c.DESIGNATION.ToString(),Amorti=c.AMORTI.ToString() }).OrderBy(o => o.ID).ToList(), JsonRequestBehavior.AllowGet);
        }
        //********************************************************************
        public JsonResult GetSousFamille(string CODE)
        {
            IMMODEMOEntities ctxt = new IMMODEMOEntities();
            var sousFamille = ctxt.IMMO_FAMILLE.OrderBy(o => o.CODE).AsQueryable();
           
              
               sousFamille = sousFamille.Where(w => w.FAMILLEM == CODE);

            
            return Json(sousFamille.Select(c => new { ID = c.CODE, Name = c.LIBELLE }).OrderBy(o => o.ID).ToList(),
                JsonRequestBehavior.AllowGet);
        }
        //**************************************
       //***************************************************************************************
        public JsonResult GetArticles([DataSourceRequest] DataSourceRequest request, string CODEM, string CODEF,string CODE)
        {
            IMMODEMOEntities ctxt = new IMMODEMOEntities();
            var Articles = ctxt.IMMO_ARTICLE.OrderBy(o => o.DESIGNATION).AsQueryable();
            
                if (CODEM != "")
                {
                    Articles = Articles.Where(w => w.IMMO_FAMILLE.FAMILLEM == CODEM);
                }



                if (CODEF != "")
                {
                    Articles = Articles.Where(w => w.IMMO_FAMILLE.CODE == CODEF);

                }

            if(CODE !="")
            {
                Articles = Articles.Where(w => w.CODE == CODE);
            }
            
            

            var ArticlesList = Articles.Select(p => new ArticleLite
            {
                CODE = p.CODE,
                DESIGNATION = p.DESIGNATION,
                DATEAQUISITION = p.DATEAQUISITION,
                FAMILLE=p.FAMILLE,
                VALEURCOMPTABLE=p.VALEURCOMPTABLE,
                AFFECTATION = p.IMMO_AFFECTATION.LIBELLE,
                LOCALE = p.LOCALE,
                TAUXAMORTISSEMENT=p.TAUXAMORTISSEMENT,
                AMORTI=p.AMORTI,
                DATEEXPLOITATION=p.DATEEXPLOITATION
               


            });
            var fvt = ArticlesList.ToList();
            
            return Json(fvt.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            
        }
        //***********************************************************************************
        public JsonResult GetArticles2( string CODEM, string CODEF)
        {
            IMMODEMOEntities ctxt = new IMMODEMOEntities();
            var Articles = ctxt.IMMO_ARTICLE.OrderBy(o => o.DESIGNATION).AsQueryable();

            if (CODEM != "")
            {
                Articles = Articles.Where(w => w.IMMO_FAMILLE.FAMILLEM == CODEM);
            }



            if (CODEF != "")
            {
                Articles = Articles.Where(w => w.IMMO_FAMILLE.CODE == CODEF);

            }



            var ArticlesList = Articles.Select( (IMMO_ARTICLE p) => new ArticleLite
            {
                CODE = p.CODE,
                DESIGNATION = p.DESIGNATION,
                DATEAQUISITION = p.DATEAQUISITION,
                ANNEEBL=p.ANNEEBL,
                DUREE=p.DUREE,
               
                FAMILLE = p.FAMILLE,
                VALEURCOMPTABLE = p.VALEURCOMPTABLE,
                AFFECTATION = p.IMMO_AFFECTATION.LIBELLE,
                LOCALE = p.LOCALE,
                 AMORTI=p.AMORTI,
                DATEEXPLOITATION=p.DATEEXPLOITATION



            });
            var fvt = ArticlesList.ToList();

            return Json(fvt, JsonRequestBehavior.AllowGet);

        }
        //***********************************************************************
        //***********************************************************************************
        public JsonResult GetArticles6(string CODE)
        {

Immo_Demo/Views/Articles/Affectation.cshtml
@using IMMO.DAL
@using IMMO.BLL
@using Immo_Demo.Models;
@using Kendo.Mvc.UI;
@{
    ViewBag.Title = "FAMILLE";
}
<script src="/Scripts/kendo/2014.3.1411/jquery.min.js"></script>

<script src="/Scripts/kendo/2014.3.1411/kendo.all.min.js"></script>
<link href="/Content/kendo/2014.3.1411/kendo.common.min.css" rel="stylesheet" />
<link href="~/Content/kendo/2014.3.1411/kendo.metro.min.css" rel="stylesheet">

<!-----debut Header*************************************-->
<!-----debut Header*************************************-->
<header>
    <div class="float-right">
        <ul id="menu">
            <li>
                <span class="k-icon k-i-group"></span>
                Immoblisations
                <ul>
                    <!--          debut test -->
                    <li>
                        @Html.ActionLink(" Mes Articles", "Index", "Articles")
                    <ul>
                        <li>@Html.ActionLink("Gestion des Familles", "Famille", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Affectations", "Affectation", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Exercices", "Exercices", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Services", "Services", "Articles")</li>

                    </ul>
                </li>
                <!--               Fin test   -->
                <li>@Html.ActionLink("Fiches d Article", "Index", "Gestion")</li>
                <li>@Html.ActionLink("Localisation", "Index", "Local")</li>
                <li>@Html.ActionLink("Ammortissement", "Index", "Ammortissement")</li>
            </ul>

        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Comptabilité
            <ul>
                <li>@Html.ActionLink(" Mes Documents", "Index", "Documents")</li>
                <li>@Html.ActionLink("Mes comptes", "Index", "Comptes")</li>
                <li>@Html.ActionLink("écritures XML", "GetAllInvCompt", "XML")</li>
            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Gestion
            <ul>
                <li>@Html.ActionLink(" Cession", "Index", "Cession")</li>
                <li>@Html.ActionLink("Mise en Rebut", "Index", "ArticleSupp")</li>
                <li>@Html.ActionLink("Code à barre", "Index", "CodeBar")</li>
                <li>@Html.ActionLink("Historique", "Index", "Historique")</li>
            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Inventaire
            <ul>
                <li>@Html.ActionLink("Inventaire", "Index", "Inventaire")</li>
                <li>@Html.ActionLink("Statistique", "Index", "Statestique")</li>
                <li>@Html.ActionLink("Gestion TVA", "Index", "TVA")</li>

            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Utilisateurs
            <ul>
                <li>@Html.ActionLink("Utilisateurs", "Index", "Utilsateurs")</li>
                <li>@Html.ActionLink("Groupes", "Index", "Role")</li>
            </ul>
        </li>
    </ul>


    <script>
        $("#menu").kendoMenu({
            animation: { open: { effects: "fadeIn" } }
        });
    </script>

</div>
<div style="float:right">
    <ul id="menu2">

        <li id="imageButton">@Html.ActionLink(" ", "Index", "Home")</li>


        @{
            if (User.Identity.IsAuthenticated)
            {
                <li>
                    <strong style="color:purple">@User.Identity.Name</strong> |
                    @{
                if (Roles.GetRolesForUser().Length > 0)
                { <strong style="color:purple">@Roles.GetRolesForUser()[0]</strong>
                }
                    }

                </li>
            }

            else
            {
                <li>@Html.ActionLink("Login", "Login", "Account")</li>


                <li>@Html.ActionLink("S inscrir", "Register", "Account")</li>

            }
            <li>
                @Html.ActionLink("Logout", "Logout", "Account")
            </li>

        }

    </ul>
    <script>
        $("#menu2").kendoMenu({
            animation: { open: { effects: "fadeIn" } }
        });
        $(document).ready(function () {


            $("#imageButton").kendoButton({
                imageUrl: "../Content/icone/home.png"
            });
        });



    </script>
    <style>
        .k-button .k-image {
            height: 25px;
        }
    </style>

</div>



</header>





<!--******** Fin Header**********************************************-->
<br /><br />
<img src='../Content/icone/fam.png' alt='ar' title='Texte à afficher1' width='75' height='75' align='left' style="padding-top:0px">

<h1 style="color:purple;font-family: 'MV Boli', arial, serif;">Gestionnaire des Affectation</h1>
<br /><br />
@(Html.Kendo().Grid<IMMO_AFFECTATION>()

        .Name("Affect")
    .AutoBind(true)


    .Columns(columns =>
                 {
                     columns.Bound(o => o.CODE).Width(100);
                     columns.Bound(o => o.LIBELLE).Width(100);
                     columns.Bound(o => o.RESPONSABLEACHAT).Width(100);




                     columns.Command(command =>
                                         {
                                             command.Edit().Text("Modifier").HtmlAttributes(new { Style = " width:106px" });
                                             command.Destroy().Text("Supprimer");

                                         }).Width(600);
                 })
    .DataSource(datasoure => datasoure.Ajax()
                                .Model(model => model.Id(record => record.CODE))
                                            .Read(read => read.Action("GetAllAff", "Historique"))
                                                    .Create(create => create.Action("Add", "Historique"))
                                                            .Update(update => update.Action("Update", "Historique"))
                                                            .Destroy(delete => delete.Action("Delete", "Historique"))






                                .PageSize(8)
                                
    )

    .Filterable()

    .ToolBar(toolbar => toolbar.Create().Text("Ajouter Affectation"))


    .Editable(editable => editable.Mode(GridEditMode.InLine))

    .Sortable()

    .Selectable()
                


    .Pageable(pageable =>
                  {
                      pageable.Refresh(true);
                      pageable.PageSizes(true);
                  })
                      
)

Immo_Demo/Views/Articles/Exercices.cshtml
@using IMMO.DAL
@using IMMO.BLL
@using Immo_Demo.Models;
@using Kendo.Mvc.UI;
@{
    ViewBag.Title = "Exercices";
}
<script src="/Scripts/kendo/2014.3.1411/jquery.min.js"></script>

<script src="/Scripts/kendo/2014.3.1411/kendo.all.min.js"></script>
<link href="/Content/kendo/2014.3.1411/kendo.common.min.css" rel="stylesheet" />
<link href="~/Content/kendo/2014.3.1411/kendo.metro.min.css" rel="stylesheet">

<!-----debut Header*************************************-->
<!-----debut Header*************************************-->
<header>
    <div class="float-right">
        <ul id="menu">
            <li>
                <span class="k-icon k-i-group"></span>
                Immoblisations
                <ul>
                    <!--          debut test -->
                    <li>
                        @Html.ActionLink(" Mes Articles", "Index", "Articles")
                    <ul>
                        <li>@Html.ActionLink("Gestion des Familles", "Famille", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Affectations", "Affectation", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Exercices", "Exercices", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Services", "Services", "Articles")</li>

                    </ul>
                </li>
                <!--               Fin test   -->
                <li>@Html.ActionLink("Fiches d Article", "Index", "Gestion")</li>
                <li>@Html.ActionLink("Localisation", "Index", "Local")</li>
                <li>@Html.ActionLink("Ammortissement", "Index", "Ammortissement")</li>
            </ul>

        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Comptabilité
            <ul>
                <li>@Html.ActionLink(" Mes Documents", "Index", "Documents")</li>
                <li>@Html.ActionLink("Mes comptes", "Index", "Comptes")</li>
                <li>@Html.ActionLink("écritures XML", "GetAllInvCompt", "XML")</li>
            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Gestion
            <ul>
                <li>@Html.ActionLink(" Cession", "Index", "Cession")</li>
                <li>@Html.ActionLink("Mise en Rebut", "Index", "ArticleSupp")</li>
                <li>@Html.ActionLink("Code à barre", "Index", "CodeBar")</li>
                <li>@Html.ActionLink("Historique", "Index", "Historique")</li>
            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Inventaire
            <ul>
                <li>@Html.ActionLink("Inventaire", "Index", "Inventaire")</li>
                <li>@Html.ActionLink("Statistique", "Index", "Statestique")</li>
                <li>@Html.ActionLink("Gestion TVA", "Index", "TVA")</li>

            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Utilisateurs
            <ul>
                <li>@Html.ActionLink("Utilisateurs", "Index", "Utilsateurs")</li>
                <li>@Html.ActionLink("Groupes", "Index", "Role")</li>
            </ul>
        </li>
    </ul>


    <script>
        $("#menu").kendoMenu({
            animation: { open: { effects: "fadeIn" } }
        });
    </script>

</div>
<div style="float:right">
    <ul id="menu2">

        <li id="imageButton">@Html.ActionLink(" ", "Index", "Home")</li>


        @{
            if (User.Identity.IsAuthenticated)
            {
                <li>
                    <strong style="color:purple">@User.Identity.Name</strong> |
                    @{
                if (Roles.GetRolesForUser().Length > 0)
                { <strong style="color:purple">@Roles.GetRolesForUser()[0]</strong>
                }
                    }

                </li>
            }

            else
            {
                <li>@Html.ActionLink("Login", "Login", "Account")</li>


                <li>@Html.ActionLink("S inscrir", "Register", "Account")</li>

            }
            <li>
                @Html.ActionLink("Logout", "Logout", "Account")
            </li>

        }

    </ul>
    <script>
        $("#menu2").kendoMenu({
            animation: { open: { effects: "fadeIn" } }
        });
        $(document).ready(function () {


            $("#imageButton").kendoButton({
                imageUrl: "../Content/icone/home.png"
            });
        });



    </script>
    <style>
        .k-button .k-image {
            height: 25px;
        }
    </style>

</div>



</header>





<!--******** Fin Header**********************************************-->
<br /><br />
<div style="display:inline-block">
    <div style="display:inline-block;float:left">
        <img src='../Content/icone/s.png' alt='ar' title='Texte à afficher1' width='75' height='75' align='left' style="padding-top:0px">

        <h1 style="color:purple;font-family: 'MV Boli', arial, serif;">Gestionnaire des Exercices</h1>
    </div>
    
</div>

<script>
    function onClick1() {
        window.location.href = "@Url.Action("Index", "Articles")"

    }
    </script>
<!--**************************************-->
<br />
@(Html.Kendo().Grid<IMMO_EXERCICE>()

        .Name("Exercices")
    .AutoBind(true)


    .Columns(columns =>
                 {
                     columns.Bound(o => o.ANNEE).Width(150);
                     columns.Bound(o => o.DATEOUVERTURE).Width(350).Format("{0:dd-MM-yyyy}").HtmlAttributes(new { style = "text-align:center;" }).HeaderHtmlAttributes(new { style = "text-align:center; " }); ;
                     columns.Bound(o => o.DATEFERMETURE).Width(350).Format("{0:dd-MM-yyyy}").HtmlAttributes(new { style = "text-align:center;" }).HeaderHtmlAttributes(new { style = "text-align:center; " }); ;
                     columns.Bound(o => o.ETAT).Width(150);




                     columns.Command(command =>
                                         {
                                             command.Edit().Text("Modifier").HtmlAttributes(new { Style = " width:106px" });
                                             command.Destroy().Text("Supprimer");

                                         }).Width(300);
                 })
    .DataSource(datasoure => datasoure.Ajax()
                                .Model(model => model.Id(record => record.ANNEE))
                                        .Read(read => read.Action("GetAlle", "Articles"))
                                                .Create(create => create.Action("Adde", "Articles"))
                                                        .Update(update => update.Action("Updatee", "Articles"))
                                                        .Destroy(delete => delete.Action("Deletee", "Articles"))






                                .PageSize(6)
    )



    .ToolBar(toolbar => toolbar.Create().Text("Ajouter Exercie"))


    .Editable(editable => editable.Mode(GridEditMode.InLine))

    .Sortable()

    .Selectable()

                .Filterable()
    .Pageable(pageable =>
                  {
                      pageable.Refresh(true);
                      pageable.PageSizes(true);
                  })
)

Immo_Demo/Views/Articles/Services.cshtml
@using IMMO.DAL
@using IMMO.BLL
@using Immo_Demo.Models;
@using Kendo.Mvc.UI;
@{
    ViewBag.Title = "Services";
}
<script src="/Scripts/kendo/2014.3.1411/jquery.min.js"></script>

<script src="/Scripts/kendo/2014.3.1411/kendo.all.min.js"></script>
<link href="/Content/kendo/2014.3.1411/kendo.common.min.css" rel="stylesheet" />
<link href="~/Content/kendo/2014.3.1411/kendo.metro.min.css" rel="stylesheet">

<!-----debut Header*************************************-->
<!-----debut Header*************************************-->
<header>
    <div class="float-right">
        <ul id="menu">
            <li>
                <span class="k-icon k-i-group"></span>
                Immoblisations
                <ul>
                    <!--          debut test -->
                    <li>
                        @Html.ActionLink(" Mes Articles", "Index", "Articles")
                    <ul>
                        <li>@Html.ActionLink("Gestion des Familles", "Famille", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Affectations", "Affectation", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Exercices", "Exercices", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Services", "Services", "Articles")</li>

                    </ul>
                </li>
                <!--               Fin test   -->
                <li>@Html.ActionLink("Fiches d Article", "Index", "Gestion")</li>
                <li>@Html.ActionLink("Localisation", "Index", "Local")</li>
                <li>@Html.ActionLink("Ammortissement", "Index", "Ammortissement")</li>
            </ul>

        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Comptabilité
            <ul>
                <li>@Html.ActionLink(" Mes Documents", "Index", "Documents")</li>
                <li>@Html.ActionLink("Mes comptes", "Index", "Comptes")</li>
                <li>@Html.ActionLink("écritures XML", "GetAllInvCompt", "XML")</li>
            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Gestion
            <ul>
                <li>@Html.ActionLink(" Cession", "Index", "Cession")</li>
                <li>@Html.ActionLink("Mise en Rebut", "Index", "ArticleSupp")</li>
                <li>@Html.ActionLink("Code à barre", "Index", "CodeBar")</li>
                <li>@Html.ActionLink("Historique", "Index", "Historique")</li>
            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Inventaire
            <ul>
                <li>@Html.ActionLink("Inventaire", "Index", "Inventaire")</li>
                <li>@Html.ActionLink("Statistique", "Index", "Statestique")</li>
                <li>@Html.ActionLink("Gestion TVA", "Index", "TVA")</li>

            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Utilisateurs
            <ul>
                <li>@Html.ActionLink("Utilisateurs", "Index", "Utilsateurs")</li>
                <li>@Html.ActionLink("Groupes", "Index", "Role")</li>
            </ul>
        </li>
    </ul>


    <script>
        $("#menu").kendoMenu({
            animation: { open: { effects: "fadeIn" } }
        });
    </script>

</div>
<div style="float:right">
    <ul id="menu2">

        <li id="imageButton">@Html.ActionLink(" ", "Index", "Home")</li>


        @{
            if (User.Identity.IsAuthenticated)
            {
                <li>
                    <strong style="color:purple">@User.Identity.Name</strong> |
                    @{
                if (Roles.GetRolesForUser().Length > 0)
                { <strong style="color:purple">@Roles.GetRolesForUser()[0]</strong>
                }
                    }

                </li>
            }

            else
            {
                <li>@Html.ActionLink("Login", "Login", "Account")</li>


                <li>@Html.ActionLink("S inscrir", "Register", "Account")</li>

            }
            <li>
                @Html.ActionLink("Logout", "Logout", "Account")
            </li>

        }

    </ul>
    <script>
        $("#menu2").kendoMenu({
            animation: { open: { effects: "fadeIn" } }
        });
        $(document).ready(function () {


            $("#imageButton").kendoButton({
                imageUrl: "../Content/icone/home.png"
            });
        });



    </script>
    <style>
        .k-button .k-image {
            height: 25px;
        }
    </style>

</div>



</header>





<!--///////////////////////////////////////////////-->
<img src='../Content/icone/hr.png' alt='ar' title='Texte à afficher1' width='75' height='75' align='left' style="padding-top:0px">

<h1 style="color:purple;font-family: 'MV Boli', arial, serif;">Gestionnaire des Services</h1>
<br /><br /><br />

@(Html.Kendo().Grid<IMMO_SERVICE>()

        .Name("Services")
    .AutoBind(true)


    .Columns(columns =>
                 {
                     columns.Bound(o => o.CODE).Width(150);
                     columns.Bound(o => o.LIBELLE).Width(350);
                     




                     columns.Command(command =>
                                         {
                                             command.Edit().Text("Modifier").HtmlAttributes(new { Style = " width:106px" });
                                             command.Destroy().Text("Supprimer");

                                         }).Width(300);
                 })
    .DataSource(datasoure => datasoure.Ajax()
                                .Model(model => model.Id(record => record.CODE))
                                        .Read(read => read.Action("GetAlls", "Articles"))
                                                .Create(create => create.Action("Adds", "Articles"))
                                                        .Update(update => update.Action("Updates", "Articles"))
                                                        .Destroy(delete => delete.Action("Deletes", "Articles"))






                                .PageSize(9)
    )



    .ToolBar(toolbar => toolbar.Create().Text("Ajouter Service"))


    .Editable(editable => editable.Mode(GridEditMode.InLine))

    .Sortable()

    .Selectable()

                .Filterable()
    .Pageable(pageable =>
                  {
                      pageable.Refresh(true);
                      pageable.PageSizes(true);
                  })
)