Immo_Demo/Controllers/UtilsateursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IMMO.DAL;
using IMMO.BLL;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.Resources;
using Kendo.Mvc.Infrastructure;
using System.Data.Entity;
using Immo_Demo.Models;
using WebMatrix.WebData;
using WebMatrix.Data;
using System.Web.Security;


namespace Immo_Demo.Controllers
{
    public class UtilsateursController : Controller
    {
        private IUtilsateurBuisness bo = new UtlisateurBuisness();
        private IRoleBuisness bo2 = new RoleBuisness();





        //*********************************************************************     
        SimpleMembershipEntities ctxt = new SimpleMembershipEntities();
        //////////////////////////Debut Conroleur Affectation///////////////////
        //************************************************************************
        public ActionResult GetAll([DataSourceRequest] DataSourceRequest request)
        {

            var Aff = bo.Afficher();
            return Json(Aff.ToDataSourceResult(request, record => new
            {
                record.Password,



            }), JsonRequestBehavior.AllowGet);
        }
        //***********************************************************************************
        public ActionResult test([DataSourceRequest] DataSourceRequest request)
        {
            
            var Articles = ctxt.Login1.OrderBy(o => o.Username).AsQueryable();

           



            var ArticlesList = Articles.Select(p => new Immo_Demo.Models.Login
            {
                Username = p.Password.ToString(),
                



            });
            var fvt = ArticlesList.ToList();

            return Json(fvt.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        //***********************************************************************
        public ActionResult ChercherUser([DataSourceRequest] DataSourceRequest request, int? RoleId)
        {
            //var C = ctxt.Login1.OrderBy(o => o.Password).AsQueryable();
            List<Login1> C = new List<Login1>();
             C = bo.Afficher();

            if (RoleId != null)
            {
                C.Clear();
                int RoleId1 = (int)RoleId;
                webpages_Roles r = bo2.Trouver(RoleId1);

                string RoleName = r.RoleName;
                var L = Roles.GetUsersInRole(RoleName).ToList();
                foreach (Login1 l in ctxt.Login1)
                {
                    string tmp = l.Password;
                    if (L.Contains(tmp) == true)
                    {
                        C.Add(l);
                    }
                }
            }


               


            var ArticlesList = C.Select(p => new Immo_Demo.Models.Login
            {
                Username = p.Password.ToString(),




            });
            var fvt = ArticlesList.ToList();







            return Json(fvt.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);

        }
        //**********************************************************************************
        //***********************************************************************************


        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Add([DataSourceRequest] DataSourceRequest request, Login1 l)
        {
            try { 

            if (l != null && ModelState.IsValid)
            {
                bo.Ajouter(l);

                ctxt.SaveChanges();
            }
            return Json(new[] { l }.ToDataSourceResult(request, ModelState));
            }
            catch { return View(); }
        }
        //**************************************************************************************

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Update([DataSourceRequest] DataSourceRequest request, Login1 l)
        {
            try { 
            if (l != null && ModelState.IsValid)
            {
                bo.Mettre_A_Jour(l);

                ctxt.SaveChanges();
            }
            return Json(ModelState.ToDataSourceResult());
            }
            catch { return View(); }
        }


        //*****************************************************************
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Delete([DataSourceRequest] DataSourceRequest request, Login1 l)
        {
            try { 
            if (l != null && ModelState.IsValid)
            {
                bo.Supprimer(l);
                ctxt.SaveChanges();
            }
            return Json(ModelState.ToDataSourceResult());
            }
            catch { return View(); }
        }
        //***********************************************************************
        [Authorize(Roles = "Administrateur")]
        // GET: Utilsateurs
        public ActionResult Index()
        {
            return View();
        }
    }
}

Immo_Demo/Views/Utilsateurs/Index.cshtml
@using IMMO.BLL;
@using IMMO.DAL;
@using Immo_Demo.Models
@model IEnumerable<Immo_Demo.Models.Login>
@{
    ViewBag.Title = "Index";
}
<script src="/Scripts/kendo/2014.3.1411/jquery.min.js"></script>
<script src="/Scripts/kendo/2014.3.1411/kendo.all.min.js"></script>
<link href="/Content/kendo/2014.3.1411/kendo.common.min.css" rel="stylesheet" />
<link href="~/Content/kendo/2014.3.1411/kendo.metroblack.css" rel="stylesheet" />
<!--***********************************************************************************-->
<!-----debut Header*************************************-->
<header>
    <div class="float-right">
        <ul id="menu">
            <li>
                <span class="k-icon k-i-group"></span>
                Immoblisations
                <ul>
                    <!--          debut test -->
                    <li>
                        @Html.ActionLink(" Mes Articles", "Index", "Articles")
                    <ul>
                        <li>@Html.ActionLink("Gestion des Familles", "Famille", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Affectations", "Affectation", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Exercices", "Exercices", "Articles")</li>
                        <li>@Html.ActionLink("Gestion des Services", "Services", "Articles")</li>

                    </ul>
                </li>
                <!--               Fin test   -->
                <li>@Html.ActionLink("Fiches d Article", "Index", "Gestion")</li>
                <li>@Html.ActionLink("Localisation", "Index", "Local")</li>
                <li>@Html.ActionLink("Ammortissement", "Index", "Ammortissement")</li>
            </ul>

        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Comptabilité
            <ul>
                <li>@Html.ActionLink(" Mes Documents", "Index", "Documents")</li>
                <li>@Html.ActionLink("Mes comptes", "Index", "Comptes")</li>
                <li>@Html.ActionLink("écritures XML", "GetAllInvCompt", "XML")</li>
            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Gestion
            <ul>
                <li>@Html.ActionLink(" Cession", "Index", "Cession")</li>
                <li>@Html.ActionLink("Mise en Rebut", "Index", "ArticleSupp")</li>
                <li>@Html.ActionLink("Code à barre", "Index", "CodeBar")</li>
                <li>@Html.ActionLink("Historique", "Index", "Historique")</li>
            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Inventaire
            <ul>
                <li>@Html.ActionLink("Inventaire", "Index", "Inventaire")</li>
                <li>@Html.ActionLink("Statistique", "Index", "Statestique")</li>
                <li>@Html.ActionLink("Gestion TVA", "Index", "TVA")</li>

            </ul>
        </li>
        <li>
            <span class="k-icon k-i-group"></span>
            Utilisateurs
            <ul>
                <li>@Html.ActionLink("Utilisateurs", "Index", "Utilsateurs")</li>
                <li>@Html.ActionLink("Groupes", "Index", "Role")</li>
            </ul>
        </li>
    </ul>


    <script>
        $("#menu").kendoMenu({
            animation: { open: { effects: "fadeIn" } }
        });
    </script>

</div>
<div style="float:right">
    <ul id="menu2">

        <li id="imageButton">@Html.ActionLink(" ", "Index", "Home")</li>


        @{
            if (User.Identity.IsAuthenticated)
            {
                <li>
                    <strong style="color:purple">@User.Identity.Name</strong> |
                    @{
                if (Roles.GetRolesForUser().Length > 0)
                { <strong style="color:purple">@Roles.GetRolesForUser()[0]</strong>
                }
                    }

                </li>
            }

            else
            {
                <li>@Html.ActionLink("Login", "Login", "Account")</li>


                <li>@Html.ActionLink("S inscrir", "Register", "Account")</li>

            }
            <li>
                @Html.ActionLink("Logout", "Logout", "Account")
            </li>

        }

    </ul>
    <script>
        $("#menu2").kendoMenu({
            animation: { open: { effects: "fadeIn" } }
        });
        $(document).ready(function () {


            $("#imageButton").kendoButton({
                imageUrl: "../Content/icone/home.png"
            });
        });



    </script>
    <style>
        .k-button .k-image {
            height: 25px;
        }
    </style>

</div>



</header>



<!--******************************************************-->
<img src='../Content/icone/avatar.png' alt='ar' title='Texte à afficher1' width='75' height='75' align='left' style="padding-top:0px">

<h1 style="color:purple;font-family: 'MV Boli', arial, serif;">Gestionnaire des Utilsateurs</h1>
<!--****************************************************************-->
<script type="text/x-kendo-tmpl" id="template">
    <div class="product">
        <img src="../Content/icone/user.png" alt="Utisateur" />
       <h3>#:Username#</h3>
       <!----<span id="undo" class="k-button" onclick="OnSelect()">Details</span>-->

    </div>

</script>

<div class="demo-section">
    @(Html.Kendo().ListView<Immo_Demo.Models.Login>()

        .Name("listView")



        .TagName("div")
        .ClientTemplateId("template")
        .DataSource(dataSource =>
                    {
                        dataSource.Model(m => m.Id("Username"));
                        dataSource.Read(read => read.Action("test", "Utilsateurs"));//.Data("ArticleAdditionalData"));
                        dataSource.PageSize(15);

                    })

        .Pageable()


                .Selectable(selectable => selectable.Mode(ListViewSelectionMode.Multiple))

    )

</div>
<!--**********************************************************************************-->



<style>
    .demo-section {
        padding: -50px;
        width: 650px;
        height: 350px;
        float: left;
        position: relative;
    }

    #listView {
        padding: 10px;
        margin-bottom: -1px;
        min-width: 555px;
        min-height: 510px;
        background-color: #CC99FF;
    }

    .product {
        float: left;
        position: relative;
        width: 111px;
        height: 170px;
        margin: 7px;
        padding: 0;
    }

        .product img {
            width: 110px;
            height: 110px;
        }

        .product h3 {
            margin: 0;
            padding: 3px 5px 0 0;
            max-width: 96px;
            overflow: hidden;
            line-height: 1.1em;
            font-size: .9em;
            font-weight: normal;
            text-transform: uppercase;
            color:#CC3300
;
        }

        .product p {
            visibility: hidden;
        }

        .product:hover p {
            visibility: visible;
            position: absolute;
            width: 110px;
            height: 110px;
            top: 0;
            margin: 0;
            padding: 0;
            line-height: 110px;
            vertical-align: middle;
            text-align: center;
            color: #fff;
            background-color: rgba(0,0,0,0.75);
            transition: background .2s linear, color .2s linear;
            -moz-transition: background .2s linear, color .2s linear;
            -webkit-transition: background .2s linear, color .2s linear;
            -o-transition: background .2s linear, color .2s linear;
        }

        .k-listview:after, .product dl:after {
            content: ".";
            display: block;
            height: 0;
            clear: both;
            visibility: hidden;
        }
</style>